"""drop demo problems table

Revision ID: acafc186cb2a
Revises: 77b32e3b1edb
Create Date: 2026-09-12 17:59:35.866828
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'acafc186cb2a'
down_revision: Union[str, None] = '77b32e3b1edb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_demo_problems_slug'), table_name='demo_problems')
    op.drop_table('demo_problems')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_problems',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expression', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('answer', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('demo_problems_pkey'))
    )
    op.create_index(op.f('ix_demo_problems_slug'), 'demo_problems', ['slug'], unique=True)
    # ### end Alembic commands ###
